// ...existing code...
function createStar() {
  // Create a 4-pointed star instead of a 5-pointed one
  const star = document.createElement('div');
  star.classList.add('star');
  // ...existing code...
}
// ...existing code...